name: Deploy .NET Linux IIS
#
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build --no-restore
   
    - name: Run the Publish
      run: dotnet publish --configuration Release --no-restore --output ./publish
      
    - name: Setup Vault Agent
      run: | 
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }} ssh Administrator@192.168.100.160 'mkdir C:\vault-agent'
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }}  ssh Administrator@192.168.100.160 'echo {{ secrets.AGENT_ROLE_ID }} > C:\vault-agent\agent-role-id'
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }}  ssh Administrator@192.168.100.160 'echo {{ secrets.AGENT_SECRET_ID }} > C:\vault-agent\agent-secret-id'

 #DEPLOYMENT PHASE
 # ssh command secure encrypted connection between two hosts over an insecure network.
 # sshpass command to run ssh without typing in password (run SSH using the keyboard-interactive password authentication mode)
 
 # As due to the IIS is running the website, IIS tend to lock the files 
 # 1st command we need to write a The App Offline file (app_offline.htm) is used by the ASP.NET Core Module to shut down an app.
 # https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/app-offline?view=aspnetcore-7.0
 
 
# scp command securely copy files/folders
# 2nd command scp copy ./publish/* specify username@networkIP:folderlocation
# 3rd command to delete App_offline.htm to unlock

    - name: Deploy to IIS Server 
      run: |
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }}  ssh Administrator@192.168.100.160 'echo "" > C:\www\gh-actions-iis-demo.com\App_Offline.htm'
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }} scp -r ./publish/* Administrator@192.168.100.160:/C:/www/gh-actions-iis-demo.com
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }} scp ./keys.tmpl Administrator@192.168.100.160:/C:/Users/Administrator/Desktop/github-actions-deployment-to-iis
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }} scp ./vault-agent.hcl Administrator@192.168.100.160:/C:/Users/Administrator/Desktop/github-actions-deployment-to-iis
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }} ssh Administrator@192.168.100.160 'vault agent -config=C:\Users\Administrator\Desktop\github-actions-deployment-to-iis\vault-agent.hcl -log-level=debug'
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }} ssh Administrator@192.168.100.160 'del C:\www\gh-actions-iis-demo.com\App_Offline.htm'
     

    - name: Cleanup
      run: |
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }} ssh Administrator@192.168.100.160 'rmdir /S /Q C:\vault-agent'
